### ISSUE TITLE
bcm2711-*.img missing

### ISSUE THREAD

**Issue by fdcon** [pyavitz/debian-image-builder#1]
Have tried to build feature branch but get this error all the time

**Comment by pyavitz** [comment]
I am going to assume that you are using the `dialog` menu interface?
Did you install all of the needed dependencies?
What OS are you running?
Are you using docker?

I am running a build now to test if this error presents its self.

**Comment by fdcon** [comment]
Hi,
Yes using the dialog menu interface. Have tried several different ways. Both using docker build and cross compile on both Debian (buster) and ubuntu 20.04.

Thanks

**Comment by pyavitz** [comment]
You must be missing dependencies?

![Screeenshot](https://i.imgur.com/PRm2sL9l.png)

Whilst inside debian-image-builder run:
`make ccompile` cross compile 
`make ncompile` native compile 

You can test this by editing the userdata.txt file.
Change: verbose=0 to verbose=1 (this will show errors in the stage1 script)
Run each command individually: `make raspi4-uboot` `make raspi4-kernel` `make rootfs` `make raspi4-image`

**Comment by fdcon** [comment]
Hi,
It wasn’t the dependencies. It was that I needed to do 
Make update

Thats the step that I missed.
Thanks for looking at it.

Sorry for missing that step.

f.

**Comment by pyavitz** [comment]
Ah yes, the docker builder. Happy you figured it out.
