### ISSUE TITLE
bpi-m4zero: Change default language to en_GB

### ISSUE THREAD

**Issue by jayofelony** [pyavitz/debian-image-builder#100]
Can you perhaps change the default language in the OS from C to en_GB when building the image?

**Comment by pyavitz** [comment]
Check in the userdata.txt, you should see;
```
LOCALE="en_US.UTF-8"
LOCALE_LC_ALL="C.UTF-8"
```

### Future proof
`make config` also creates a profile.txt, which you can edit and `make config` will use as its defaults.

Uncomment what applies to you and edit the variables;
```
#LOCALE="en_US.UTF-8"
#LOCALE_LC_ALL="C.UTF-8"
```
