### ISSUE TITLE
 debian-image-builder vs rpi-img-builder

### ISSUE THREAD

**Issue by djsftree** [pyavitz/debian-image-builder#25]
Which do you suggest for Debian / RPI4?

**Comment by pyavitz** [comment]
The pi builder pulls its kernel from the [Raspberry Pi Github](https://github.com/raspberrypi/linux), so it benefits from the work they put into it. Bug fixes, defconfigs. code changes and what have you? I would say the pi builder is better for those who want that support.

The Pi4 was added to this builder to watch the progression of mainline Linux on the board more than anything else. Although last I checked it works fine `on a headless level`, I wouldn't use it for production. Unless you are trying to do something specific that is and don't require the Foundations efforts in that Linux space.

**Comment by djsftree** [comment]
Understood, many thanks!
