### ISSUE TITLE
Request for standard Github payment processor for sponsorship (ie, not Paypal)

### ISSUE THREAD

**Issue by em-winterschon** [pyavitz/debian-image-builder#38]
I'd like to add this project to my list of monthly github developer donation/sponsorships but using paypal is not a relevant option. Offering the built-in github sponsorship payment processor would be preferred. 

Thanks!

**Comment by pyavitz** [comment]
Thank you. I'll look into it and let you know if and when its set up.

**Comment by pyavitz** [comment]
Unless something changes in the future, I won't be opening an exclusive account to receive donation/sponsorships. Accounts aren't free and although a sponsorship would be great, there is no guarantee that it won't eventually dry up and leave me with the expense of having the account. Currently Paypal is the best option for me. I'm sorry it isn't for you, but I do very much appreciate your interest in the project.
