### ISSUE TITLE
Nanopi R5S - Fair Queue, tweak kernel NET_SCH_FQ_CODEL and NET_SCH_FQ options

### ISSUE THREAD

**Issue by 9bx154** [pyavitz/debian-image-builder#41]
Add to /debian-image-builder/defconfig/rockchip64-rk356x_defconfig this options:
```
CONFIG_NET_SCH_FQ_CODEL=y
CONFIG_NET_SCH_FQ=y
```

**Comment by pyavitz** [comment]
It's up. `#5` https://github.com/pyavitz/binary/releases/tag/images

**Comment by 9bx154** [comment]
Great, in #5 FQ and bonding work fine.
Thanks!

**Comment by pyavitz** [comment]
You are welcome
