### ISSUE TITLE
misleading error message if curl not installed

### ISSUE THREAD

**Issue by dieselnutjob** [pyavitz/debian-image-builder#46]
Hi
Line 13 of install.sh contains a connectivity check to github.com
It is intended to produce an error message about internet connection if the program cannot hit github.com
However it also produces the same error message if curl is not installed.
I suggest that you make a test for installation of curl and produce a "curl not installed" error rather than "internet connection failure" message in that scenario,

**Comment by pyavitz** [comment]
https://github.com/pyavitz/debian-image-builder/commit/6be59f377d33c776f4ed00124e5674e5fa8912e9
