### ISSUE TITLE
USB Drive support

### ISSUE THREAD

**Issue by ShorTie8** [pyavitz/debian-image-builder#63]
This patch allows you to install to a usb device using inotify-wait.
So it ends up being like a 6k patch and a Find_USB script.
make usb board=rock5b, calls Find_USB and writes the drive to USB_Drive.txt.
USB_Drive.txt is used to determine whether to use losetup or not.

[USB.patch](https://github.com/pyavitz/debian-image-builder/files/11315142/USB.patch)
[Find_USB.txt](https://github.com/pyavitz/debian-image-builder/files/11315143/Find_USB.txt)

**Comment by pyavitz** [comment]
What exactly am I looking at here? Is it writing an img created by the builder, to USB, from the builder?

**Comment by ShorTie8** [comment]
Instead of creating a image, writing to a loopback, it uses /dev/sdX, a usb device.

**Comment by pyavitz** [comment]
Well when you and github become friends create a PR.

**Comment by ShorTie8** [comment]
I reversed my comment and it killed the pr, lol.
So we start out adding in USB_Drive into custom.txt bye,

diff --git a/lib/dialog/config b/lib/dialog/config
index 5c9df0e3..73838641 100755
--- a/lib/dialog/config
+++ b/lib/dialog/config
@@ -213,6 +213,9 @@ echo "" >> custom.txt
 echo "# Compression Types: xz zst" >> custom.txt
 echo 'IMG_COMPRESSION="xz"' >> custom.txt
 echo "" >> custom.txt
+echo "# USB  Drive: sdX" >> custom.txt
+echo 'USB_Drive=""' >> custom.txt
+echo "" >> custom.txt
 echo "### DO NOT EDIT BELOW THIS LINE" >> custom.txt
 echo "# CUSTOM=${BUILDER}" >> custom.txt
}


??

**Comment by ShorTie8** [comment]
Gona do up a more generic Dev_Device for all
