### ISSUE TITLE
Can't build rootfs

### ISSUE THREAD

**Issue by johnrosshunt** [pyavitz/debian-image-builder#73]
Love this utility!  You helped give new life to my Odroid N2+.

But, I can no longer build a rootfs image because in commit [da1e87c](https://github.com/pyavitz/debian-image-builder/commit/da1e87c62d5409194820d5344999f4f326350eac#diff-bd8c64a130e4a1b22c4c8fac475bd9d509665e03b31ba3851ef90b72b7c469de), line 20 of scripts/rootfs, you support building images only on Raspbian x86_64.

That seems rather restrictive. 😎

**Comment by pyavitz** [comment]
Oops. Sorry about that. Should be fixed now.
