### ISSUE TITLE
is possible to use npu in M2S board image?

### ISSUE THREAD

**Issue by zjd1988** [pyavitz/debian-image-builder#79]
excellent work!!!! I have a M2S board, but official image cannot run ai model on npu. Is possible to make npu work with your image?

**Comment by pyavitz** [comment]
What kernel are you using? As far as I know npu isn't available on 6.1. You would need to be using the current stable, 6.5.4.

Now does this work or not, I'm not sure? But I know it is in the DTS.

**Comment by zjd1988** [comment]
@pyavitz I downloaded image from official website，maybe consistent with https://github.com/BPI-SINOVOIP/BPI-M2S-bsp.git

**Comment by pyavitz** [comment]
The official imgs use an old BSP kernel, in this case forked from Hardkernel, which are also now subsequently EOL. If you were able to get NPU to work, I would think you would have a better chance doing so using the latest stable Kernel. What that entails beyond having it available in the DTS, I have no clue. I suspect the NPU driver needs to be enabled in the kernel?

**Comment by zjd1988** [comment]
@pyavitz Thank you for your suggestion. I will have a try.
