### ISSUE TITLE
bpi-m4zero: thermal protection

### ISSUE THREAD

**Issue by jayofelony** [pyavitz/debian-image-builder#98]
```
Message from syslogd@pwnagotchi at Feb 10 17:37:44 ...
 kernel:thermal thermal_zone0: gpu-thermal: critical temperature reached, shutting down

Message from syslogd@pwnagotchi at Feb 10 17:37:44 ...
 kernel:reboot: HARDWARE PROTECTION shutdown (Temperature too high)
```
I am running it headless over OTG/USB1.

**Comment by pyavitz** [comment]
what kernel? 6.1.y vendor?

Odd as I was just testing a 6.6.y build and ran into the same issue. Which is why I'm asking.

**Comment by pyavitz** [comment]
> ```
> Message from syslogd@pwnagotchi at Feb 10 17:37:44 ...
>  kernel:thermal thermal_zone0: gpu-thermal: critical temperature reached, shutting down
> 
> Message from syslogd@pwnagotchi at Feb 10 17:37:44 ...
>  kernel:reboot: HARDWARE PROTECTION shutdown (Temperature too high)
> ```
> 
> I am running it headless over OTG/USB1.

Anyway... Not sure what ur doing headless, but It looks to me you over extended and it tripped and shutdown to save its self. Put some heat sinks on it and adjust the scaling.

```
governor -h
CPU frequency scaling
Usage: 

	-c	Conservative
	-o	Ondemand
	-p	Performance
	-s	Schedutil

	-r	Run
	-u	Update
```

**Comment by jayofelony** [comment]
6.1 kernel, doing nothing fancy actually. Not using the GPU for sure. It has a full on heatsink and 2 thick thermal pads, might just put a thermal pad on the GPU as well probably.

**Comment by pyavitz** [comment]
This kernel is hackery and mainline still has a ways to go.
